/*
 * GeniusReferrals.UWP
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using GeniusReferrals.UWP;
using GeniusReferrals.UWP.Utilities;

namespace GeniusReferrals.UWP.Models
{
    public class ForceBonuses : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string advocateToken;
        private string reference;
        private int bonusAmount;

        /// <summary>
        /// The referral's token.
        /// </summary>
        [JsonProperty("advocate_token")]
        public string AdvocateToken 
        { 
            get 
            {
                return this.advocateToken; 
            } 
            set 
            {
                this.advocateToken = value;
                onPropertyChanged("AdvocateToken");
            }
        }

        /// <summary>
        /// The reference number for this request. Usually the order_id, payment_id, or timestamp.
        /// </summary>
        [JsonProperty("reference")]
        public string Reference 
        { 
            get 
            {
                return this.reference; 
            } 
            set 
            {
                this.reference = value;
                onPropertyChanged("Reference");
            }
        }

        /// <summary>
        /// The bonus amount to give to the advocate.
        /// </summary>
        [JsonProperty("bonus_amount")]
        public int BonusAmount 
        { 
            get 
            {
                return this.bonusAmount; 
            } 
            set 
            {
                this.bonusAmount = value;
                onPropertyChanged("BonusAmount");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 