/*
 * GeniusReferrals.UWP
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/17/2017
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using GeniusReferrals.UWP;
using GeniusReferrals.UWP.Utilities;

namespace GeniusReferrals.UWP.Models
{
    public class Referral : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string referredAdvocateToken;
        private string referralOriginSlug;
        private string campaignSlug;
        private string httpReferer;

        /// <summary>
        /// The referrals token
        /// </summary>
        [JsonProperty("referred_advocate_token")]
        public string ReferredAdvocateToken 
        { 
            get 
            {
                return this.referredAdvocateToken; 
            } 
            set 
            {
                this.referredAdvocateToken = value;
                onPropertyChanged("ReferredAdvocateToken");
            }
        }

        /// <summary>
        /// The referral origin identifier
        /// </summary>
        [JsonProperty("referral_origin_slug")]
        public string ReferralOriginSlug 
        { 
            get 
            {
                return this.referralOriginSlug; 
            } 
            set 
            {
                this.referralOriginSlug = value;
                onPropertyChanged("ReferralOriginSlug");
            }
        }

        /// <summary>
        /// The campaign identifier
        /// </summary>
        [JsonProperty("campaign_slug")]
        public string CampaignSlug 
        { 
            get 
            {
                return this.campaignSlug; 
            } 
            set 
            {
                this.campaignSlug = value;
                onPropertyChanged("CampaignSlug");
            }
        }

        /// <summary>
        /// The http_referrer URL
        /// </summary>
        [JsonProperty("http_referer")]
        public string HttpReferer 
        { 
            get 
            {
                return this.httpReferer; 
            } 
            set 
            {
                this.httpReferer = value;
                onPropertyChanged("HttpReferer");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 